### ISSUE TITLE
Consider switching to ObjectId from UUID

### ISSUE THREAD

**Issue by dancsi** [tozti/tozti#12]
Currently, we are using UUIDs as object ids. However, I just realized that Mongo has its own unique object id type - [`ObjectId`](https://docs.mongodb.com/manual/reference/method/ObjectId/). According to [this post](https://stackoverflow.com/a/22607171) on StackOverflow, there are some nice performance advantages of using ObjectId instead of UUID. 
On the other hand, it would destroy our beautiful schema :/ @Lapin0t, @poechsel, @jetSett, what do you think?

**Comment by Lapin0t** [comment]
What specific aspect of the performance would be improved? You mean the size of the DB (because uuids are larger than objectids)? Also i'm not sure the post is really applicable since we are using UUIDv4 (that is, purely random UUIDs, not time/machine/organization deterministic UUIDs) and we generate them on the server, not the client.

**Comment by Lapin0t** [comment]
If the arguments were convincing enough i guess we can close the issue.

**Comment by dancsi** [comment]
In all fairness, I think I delayed thinking about this issue for some time, but now that I read it again, unless we run into some major performance problems relating to the UUIDs, you are right.
