### ISSUE TITLE
Why did you remove the sample extension?

### ISSUE THREAD

**Issue by dancsi** [tozti/tozti#8]
The question is in the title. It would be nice to add back the sample extension, for testing purposes.

**Comment by flupe** [comment]
Well I think the issue was that it does not really belong to the tozti core codebase. @poechsel intends to put the previous hello-world extension in its own repo, so that you can freely clone it for testing.
Actually, I think we should go as far as to recommend the hello-world extension as a starting point when creating an *official* extension. So suggesting in the documentation to clone this repo to start developing a new extension. This way we can provide a default reliable build system.

**Comment by flupe** [comment]
As I said, @poechsel added really simple examples on [this repo](https://github.com/tozti/). Some other should be coming soon.
